name: Branche CI

on:
  push:
    branches: [ TOOLING_setup_github_actions ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

  test-unit:
    needs: setup
    runs-on: windows-latest
    steps:
      - run: npm unit

  test-features:
    needs: test-unit
    runs-on: windows-latest
    steps:
      - run: npm cucumber

  build:
    needs: test-features
    runs-on: windows-latest
    steps:
      - run: npm run build