name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  test:
    name: Test net execution
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'release'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Unit test execution
        run: npm run unit

      - name: Functional test execution
        run: npm run cucumber

  sonarcloud:
    name: SonarCloud
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'release'
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Compute unit test coverage
        run: npm run unit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    needs: sonarcloud
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'release'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  publish-npm:
    name: Publish to npmjs
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'release'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM2_TOKEN }}

#  publish-github:
#    name: Publish to GitHub Packages
#    needs: build
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          ref: 'release'
#
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '19.x'
#          cache: 'npm'
#          registry-url: 'https://npm.pkg.github.com'
#          scope: '@desvart'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Publish
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GTH_TOKEN }}