name: Test-release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  test:
    name: Test net execution
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Unit test execution
        run: npm run unit

      - name: Functional test execution
        run: npm run cucumber

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Compute unit test coverage
        run: npm run unit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}